// <auto-generated />
using System;
using DUSCoreTraining.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DUSCoreTraining.Migrations
{
    [DbContext(typeof(ModelRechnung))]
    partial class ModelRechnungModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DUSCoreTraining.Models.Positionen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anzahl");

                    b.Property<float>("Preis");

                    b.Property<int>("RechnungID");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("RechnungID");

                    b.ToTable("Positionens");
                });

            modelBuilder.Entity("DUSCoreTraining.Models.Rechnung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<string>("KopfText");

                    b.Property<int>("KundenID");

                    b.Property<float>("Summe");

                    b.HasKey("ID");

                    b.ToTable("Rechnungs");
                });

            modelBuilder.Entity("DUSCoreTraining.Models.Positionen", b =>
                {
                    b.HasOne("DUSCoreTraining.Models.Rechnung", "Rechnung")
                        .WithMany("Postionen")
                        .HasForeignKey("RechnungID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
